---

- name: "platform: all"
  color: "d93f0b"
  aliases: []
- name: "platform: unix"
  color: "d93f0b"
  aliases: []
- name: "platform: windows"
  color: "d93f0b"
  aliases: []
- name: "status: accepted"
  color: "0e8a16"
  aliases: []
- name: "status: duplicate"
  color: "0e8a16"
  aliases: []
- name: "status: fixed"
  color: "0e8a16"
  aliases: []
- name: "status: invalid"
  color: "0e8a16"
  aliases: []
- name: "status: obsolete"
  color: "0e8a16"
  aliases: []
- name: "status: research"
  color: "0e8a16"
  aliases: []
- name: "status: won't fix"
  color: "0e8a16"
  aliases: []
- name: "type: addition"
  color: "fbca04"
  aliases: []
- name: "type: bug"
  color: "b60205"
  aliases: []
- name: "type: discussion"
  color: "fbca04"
  aliases: []
- name: "type: documentation"
  color: "fbca04"
  aliases: []
- name: "type: enhancement"
  color: "fbca04"
  aliases: []
- name: "type: performance"
  color: "fbca04"
  aliases: []
- name: "type: question"
  color: "fbca04"
  aliases: []
