language: python
dist: bionic
python:
- '3.9.15'
before_install:
- sudo apt-get -y install upx
- pip install poetry setuptools --upgrade
script:
- "unset MY_RUBY_HOME"
- "./scripts/workflow.sh test"
- "./scripts/workflow.sh build"
- "./dist/temply --version"
deploy:
  provider: releases
  api_key:
    secure: ge4o8JMNiI4gOeiQDZk4cH8Y/yRCmpmP3H/ELbA3pfC2wrJYzoZUiFQx4ZY6MaLQHNcFHpobHZ8yyvpNgDQfrZAoyBOgqUL6yj25HONi3HE+ywHHlv4wODVt6ZLujd4rBgWuJXgaZpkgC/ZOItBgamf/RtrOIGDTofLknCmOSlkraCKGCDj4Ct/7p20mflNo1owvhjxDstum2p5sIAe+PCIXieCyeRvON42r0Eu7RX6nlF2x8J9ILs46h+3nmo84LgMNWE/pBnEOGS4NA0KWTv7VqhvFFd3E8ATMdhS0PA99JQo4BFP44mpJpWCxZLcbOSC5gQXCQv9Nv0Hn0v3VEVMVORSTNHQKGQakfrNboDtV88g5KGnvf6vVnsZDB2DEU5acjgu9e91i8LkEfgCN/nxe5BPaOqJgrsXOWCSdQcCY4SC1Oyt1eHXN2Dartcd/rJ4n/8t9e3jqvfW1Svcml3r9+rfOV68mnREvYVAbFHl0dCdyux20OL2h6DER5o+iSsuWbay6XZrgAkhIl3SIsldgnxsD/SItPzOuDr2AEWjXUPorvLS0WjNTxAaZ8eU3M39fDM7LVSvqDM6cex4y9lxlUtWAcafrMArfGLXHtAgIw3FhkEbrI4Bj3zdsMasJcR1Y0gUS0yInnmS+IC0Z1jochzbrTi3446bSwD1UVvY=
  file: dist/temply
  on:
    repo: amannocci/temply
    tags: true
  skip_cleanup: 'true'
