---
name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Lint
        run: uv run poe lint

  build:
    needs:
      - lint
    strategy:
      matrix:
        os:
          - runner: macos-14
            target: darwin-arm64
          - runner: macos-13
            target: darwin-amd64
          - runner: ubuntu-22.04
            target: linux-amd64
          - runner: ubuntu-22.04-arm
            target: linux-arm64
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Build
        run: uv run poe build

      - uses: actions/upload-artifact@v4
        with:
          name: temply-tarball-${{ matrix.os.target }}
          path: dist/

  test:
    needs:
      - build
    strategy:
      matrix:
        os:
          - runner: macos-14
            target: darwin-arm64
          - runner: macos-13
            target: darwin-amd64
          - runner: ubuntu-22.04
            target: linux-amd64
          - runner: ubuntu-22.04-arm
            target: linux-arm64
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Test
        run: uv run poe test
