---

name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-interaction

      - name: Lint
        run: poetry run poe lint

      - name: Build
        run: poetry run poe build

      - name: Test
        run: poetry run poe test
